// <auto-generated />
using GICTask;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GICTask.Migrations
{
    [DbContext(typeof(PopulationContext))]
    partial class PopulationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("GICTask.Model.Actuals", b =>
                {
                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualHouseholds")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualPopulation")
                        .HasColumnType("REAL");

                    b.HasKey("State");

                    b.ToTable("Actuals");
                });

            modelBuilder.Entity("GICTask.Model.Estimates", b =>
                {
                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Districts")
                        .HasColumnType("INTEGER");

                    b.Property<float>("EstimatesHouseholds")
                        .HasColumnType("REAL");

                    b.Property<float>("EstimatesPopulation")
                        .HasColumnType("REAL");

                    b.HasKey("State", "Districts");

                    b.ToTable("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
